### ISSUE TITLE
Tests break on latest commits

### ISSUE THREAD

**Issue by hadiasghari** [citp/OpenWPM#158]
Hi, perhaps I'm doing something wrong, but I the tests have stopped working after the latest commit and switch to Selenium 3:

```
$ py.test -vv
============================================================================= test session starts =====================================================
platform linux2 -- Python 2.7.13, pytest-3.2.3, py-1.4.34, pluggy-0.4.0 -- /home/hadi/.virtualenvs/openwpm/bin/python2
cachedir: .cache
rootdir: /home/hadi/devel/OpenWPM/clone-201710/OpenWPM, inifile:
collected 44 items / 1 errors                                                                                                                                                   

==================================================================================== ERRORS ===========================================================
_____________________________________________________________________ ERROR collecting test/manual_test.py ____________________________________________
ImportError while importing test module '/home/hadi/devel/OpenWPM/clone-201710/OpenWPM/test/manual_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/home/hadi/.virtualenvs/openwpm/lib/python2.7/site-packages/_pytest/python.py:395: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/home/hadi/.virtualenvs/openwpm/lib/python2.7/site-packages/py/_path/local.py:662: in pyimport
    __import__(modname)
/home/hadi/.virtualenvs/openwpm/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:212: in load_module
    py.builtin.exec_(co, mod.__dict__)
test/manual_test.py:12: in <module>
    from automation.DeployBrowsers import configure_firefox
E   ImportError: No module named automation.DeployBrowsers
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=========================================================================== 1 error in 0.37 seconds ===================================================
```

Please advise, as I was in the midst of a new addition to the platform for detecting cookie-banners. Btw, great job with updating to newer Selenium/Python/Firefox.

-Hadi

**Comment by englehardt** [comment]
The problem seem to be that pytest is trying to execute the `manual_test.py` file. Normally this file should only be run manually, by running `python -m test.manual_test` from the root of the OpenWPM directory.

I thought pytest only gathered files with the prefix `test_`, but I guess something in the most recent merge (or a new version of pytest) changed that. https://github.com/citp/OpenWPM/commit/4bed6b0960c7d7ef5ae13865848587253db07e38 should fix this issue.

**Comment by hadiasghari** [comment]
@englehardt  thanks for the quick response. Unfortunately the problem is not fixed. If I run py.test directly on any test, e.g. `py.test test/test_crawl.py`, I get the error below. Perhaps some local changes were not pushed?

```
$ py.test test/test_crawl.py 
...
__________________________________________________________ ERROR at setup of TestCrawl.test_browser_profile_coverage ______________________________________

request = <SubRequest 'prepare_test_setup' for <Function 'test_browser_profile_coverage'>>

    @pytest.fixture(scope="session", autouse=True)
    def prepare_test_setup(request):
        """Run an HTTP server during the tests."""
>       create_xpi()

test/conftest.py:23: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/conftest.py:15: in create_xpi
    cwd="../automation/Extension/firefox/")
/usr/lib64/python2.7/subprocess.py:181: in check_call
    retcode = call(*popenargs, **kwargs)
/usr/lib64/python2.7/subprocess.py:168: in call
    return Popen(*popenargs, **kwargs).wait()
/usr/lib64/python2.7/subprocess.py:390: in __init__
    errread, errwrite)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <subprocess.Popen object at 0x7f5eb1588190>, args = ['jpm', 'xpi'], executable = 'jpm', preexec_fn = None, close_fds = False, cwd = '../automation/Extension/firefox/'
env = None, universal_newlines = False, startupinfo = None, creationflags = 0, shell = False, to_close = set([]), p2cread = None, p2cwrite = None, c2pread = None
c2pwrite = None, errread = None, errwrite = None

    def _execute_child(self, args, executable, preexec_fn, close_fds,
                       cwd, env, universal_newlines,
                       startupinfo, creationflags, shell, to_close,
                       p2cread, p2cwrite,
                       c2pread, c2pwrite,
                       errread, errwrite):
        ...
        if data != "":
            try:
                _eintr_retry_call(os.waitpid, self.pid, 0)
            except OSError as e:
                if e.errno != errno.ECHILD:
                    raise
            child_exception = pickle.loads(data)
>           raise child_exception
E           OSError: [Errno 2] No such file or directory: '../automation/Extension/firefox/'

/usr/lib64/python2.7/subprocess.py:1024: OSError
=================================================================================================================
```

**Comment by englehardt** [comment]
This is probably caused by us using relative locations within some of the tests. Try running `py.test test_crawl.py` from within the `/test` directory. Does that work?

**Comment by hadiasghari** [comment]
That worked, thanks!
